# Form implementation generated from reading ui file 'plugin_builder_dialog_base.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_PluginBuilderDialogBase(object):
    def setupUi(self, PluginBuilderDialogBase):
        PluginBuilderDialogBase.setObjectName("PluginBuilderDialogBase")
        PluginBuilderDialogBase.resize(512, 413)
        PluginBuilderDialogBase.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(PluginBuilderDialogBase)
        self.gridLayout.setObjectName("gridLayout")
        self.next_button = QtWidgets.QPushButton(parent=PluginBuilderDialogBase)
        self.next_button.setObjectName("next_button")
        self.gridLayout.addWidget(self.next_button, 2, 2, 1, 1)
        self.prev_button = QtWidgets.QPushButton(parent=PluginBuilderDialogBase)
        self.prev_button.setObjectName("prev_button")
        self.gridLayout.addWidget(self.prev_button, 2, 1, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(parent=PluginBuilderDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Help
        )
        self.button_box.setObjectName("button_box")
        self.gridLayout.addWidget(self.button_box, 2, 0, 1, 1)
        self.title_label = QtWidgets.QLabel(parent=PluginBuilderDialogBase)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.gridLayout.addWidget(self.title_label, 0, 0, 1, 1)
        self.button_box2 = QtWidgets.QDialogButtonBox(parent=PluginBuilderDialogBase)
        self.button_box2.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
        )
        self.button_box2.setObjectName("button_box2")
        self.gridLayout.addWidget(self.button_box2, 2, 3, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=PluginBuilderDialogBase)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page0 = QtWidgets.QWidget()
        self.page0.setObjectName("page0")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.module_name = QtWidgets.QLineEdit(parent=self.page0)
        self.module_name.setMinimumSize(QtCore.QSize(0, 0))
        self.module_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.module_name.setText("")
        self.module_name.setObjectName("module_name")
        self.gridLayout_3.addWidget(self.module_name, 4, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_3.addItem(spacerItem, 6, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.description = QtWidgets.QLineEdit(parent=self.page0)
        self.description.setMinimumSize(QtCore.QSize(0, 0))
        self.description.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.description.setText("")
        self.description.setObjectName("description")
        self.gridLayout_3.addWidget(self.description, 3, 1, 1, 2)
        self.author = QtWidgets.QLineEdit(parent=self.page0)
        self.author.setMinimumSize(QtCore.QSize(0, 0))
        self.author.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.author.setText("")
        self.author.setObjectName("author")
        self.gridLayout_3.addWidget(self.author, 8, 1, 1, 2)
        self.plugin_name_label = QtWidgets.QLabel(parent=self.page0)
        self.plugin_name_label.setMinimumSize(QtCore.QSize(0, 0))
        self.plugin_name_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plugin_name_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.plugin_name_label.setObjectName("plugin_name_label")
        self.gridLayout_3.addWidget(self.plugin_name_label, 2, 0, 1, 1)
        self.class_name_label = QtWidgets.QLabel(parent=self.page0)
        self.class_name_label.setMinimumSize(QtCore.QSize(0, 0))
        self.class_name_label.setMaximumSize(QtCore.QSize(16772215, 16777215))
        self.class_name_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.class_name_label.setObjectName("class_name_label")
        self.gridLayout_3.addWidget(self.class_name_label, 1, 0, 1, 1)
        self.email_address = QtWidgets.QLineEdit(parent=self.page0)
        self.email_address.setMinimumSize(QtCore.QSize(0, 0))
        self.email_address.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.email_address.setText("")
        self.email_address.setObjectName("email_address")
        self.gridLayout_3.addWidget(self.email_address, 9, 1, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_3.addItem(spacerItem2, 5, 2, 1, 1)
        self.plugin_version_label = QtWidgets.QLabel(parent=self.page0)
        self.plugin_version_label.setMinimumSize(QtCore.QSize(0, 0))
        self.plugin_version_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plugin_version_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.plugin_version_label.setObjectName("plugin_version_label")
        self.gridLayout_3.addWidget(self.plugin_version_label, 5, 0, 1, 1)
        self.qgis_minimum_version = QtWidgets.QLineEdit(parent=self.page0)
        self.qgis_minimum_version.setMinimumSize(QtCore.QSize(60, 0))
        self.qgis_minimum_version.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.qgis_minimum_version.setObjectName("qgis_minimum_version")
        self.gridLayout_3.addWidget(self.qgis_minimum_version, 6, 1, 1, 1)
        self.author_label = QtWidgets.QLabel(parent=self.page0)
        self.author_label.setMinimumSize(QtCore.QSize(0, 0))
        self.author_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.author_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.author_label.setObjectName("author_label")
        self.gridLayout_3.addWidget(self.author_label, 8, 0, 1, 1)
        self.module_name_label = QtWidgets.QLabel(parent=self.page0)
        self.module_name_label.setMinimumSize(QtCore.QSize(0, 0))
        self.module_name_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.module_name_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.module_name_label.setObjectName("module_name_label")
        self.gridLayout_3.addWidget(self.module_name_label, 4, 0, 1, 1)
        self.title = QtWidgets.QLineEdit(parent=self.page0)
        self.title.setMinimumSize(QtCore.QSize(0, 0))
        self.title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.title.setText("")
        self.title.setObjectName("title")
        self.gridLayout_3.addWidget(self.title, 2, 1, 1, 2)
        self.email_address_label = QtWidgets.QLabel(parent=self.page0)
        self.email_address_label.setMinimumSize(QtCore.QSize(0, 0))
        self.email_address_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.email_address_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.email_address_label.setObjectName("email_address_label")
        self.gridLayout_3.addWidget(self.email_address_label, 9, 0, 1, 1)
        self.plugin_version = QtWidgets.QLineEdit(parent=self.page0)
        self.plugin_version.setMinimumSize(QtCore.QSize(60, 0))
        self.plugin_version.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plugin_version.setObjectName("plugin_version")
        self.gridLayout_3.addWidget(self.plugin_version, 5, 1, 1, 1)
        self.class_name = QtWidgets.QLineEdit(parent=self.page0)
        self.class_name.setMinimumSize(QtCore.QSize(0, 0))
        self.class_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.class_name.setText("")
        self.class_name.setObjectName("class_name")
        self.gridLayout_3.addWidget(self.class_name, 1, 1, 1, 2)
        self.qgis_minimum_version_label = QtWidgets.QLabel(parent=self.page0)
        self.qgis_minimum_version_label.setMinimumSize(QtCore.QSize(0, 0))
        self.qgis_minimum_version_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.qgis_minimum_version_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.qgis_minimum_version_label.setObjectName("qgis_minimum_version_label")
        self.gridLayout_3.addWidget(self.qgis_minimum_version_label, 6, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_3.addItem(spacerItem3, 10, 1, 1, 1)
        self.description_label = QtWidgets.QLabel(parent=self.page0)
        self.description_label.setMinimumSize(QtCore.QSize(0, 0))
        self.description_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.description_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.description_label.setObjectName("description_label")
        self.gridLayout_3.addWidget(self.description_label, 3, 0, 1, 1)
        self.qgis_maximum_version_label = QtWidgets.QLabel(parent=self.page0)
        self.qgis_maximum_version_label.setObjectName("qgis_maximum_version_label")
        self.gridLayout_3.addWidget(self.qgis_maximum_version_label, 7, 0, 1, 1)
        self.qgis_maximum_version = QtWidgets.QLineEdit(parent=self.page0)
        self.qgis_maximum_version.setObjectName("qgis_maximum_version")
        self.gridLayout_3.addWidget(self.qgis_maximum_version, 7, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_3.addItem(spacerItem4, 7, 2, 1, 1)
        self.qgis_minimum_version.raise_()
        self.description.raise_()
        self.class_name_label.raise_()
        self.author.raise_()
        self.module_name.raise_()
        self.plugin_version_label.raise_()
        self.qgis_minimum_version_label.raise_()
        self.author_label.raise_()
        self.plugin_version.raise_()
        self.title.raise_()
        self.email_address.raise_()
        self.module_name_label.raise_()
        self.description_label.raise_()
        self.plugin_name_label.raise_()
        self.email_address_label.raise_()
        self.class_name.raise_()
        self.qgis_maximum_version_label.raise_()
        self.qgis_maximum_version.raise_()
        self.stackedWidget.addWidget(self.page0)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox = QtWidgets.QGroupBox(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.about = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.about.setDocumentTitle("")
        self.about.setTabStopDistance(80.0)
        self.about.setObjectName("about")
        self.gridLayout_6.addWidget(self.about, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.template_cbox = QtWidgets.QComboBox(parent=self.page1)
        self.template_cbox.setObjectName("template_cbox")
        self.gridLayout_5.addWidget(self.template_cbox, 0, 1, 1, 1)
        self.template_label = QtWidgets.QLabel(parent=self.page1)
        self.template_label.setMinimumSize(QtCore.QSize(0, 0))
        self.template_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.template_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.template_label.setObjectName("template_label")
        self.gridLayout_5.addWidget(self.template_label, 0, 0, 1, 1)
        self.template_frame = QtWidgets.QFrame(parent=self.page1)
        self.template_frame.setObjectName("template_frame")
        self.frame_layout = QtWidgets.QGridLayout(self.template_frame)
        self.frame_layout.setObjectName("frame_layout")
        self.gridLayout_5.addWidget(self.template_frame, 2, 0, 1, 2)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.help_cb = QtWidgets.QCheckBox(parent=self.page2)
        self.help_cb.setChecked(True)
        self.help_cb.setObjectName("help_cb")
        self.gridLayout_4.addWidget(self.help_cb, 1, 0, 1, 2)
        self.tests_cb = QtWidgets.QCheckBox(parent=self.page2)
        self.tests_cb.setChecked(True)
        self.tests_cb.setObjectName("tests_cb")
        self.gridLayout_4.addWidget(self.tests_cb, 2, 0, 2, 2)
        self.i18n_cb = QtWidgets.QCheckBox(parent=self.page2)
        self.i18n_cb.setChecked(True)
        self.i18n_cb.setObjectName("i18n_cb")
        self.gridLayout_4.addWidget(self.i18n_cb, 0, 0, 1, 2)
        self.pb_tool_cb = QtWidgets.QCheckBox(parent=self.page2)
        self.pb_tool_cb.setChecked(True)
        self.pb_tool_cb.setObjectName("pb_tool_cb")
        self.gridLayout_4.addWidget(self.pb_tool_cb, 6, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_4.addItem(spacerItem5, 7, 0, 1, 2)
        self.makefile_cb = QtWidgets.QCheckBox(parent=self.page2)
        self.makefile_cb.setChecked(True)
        self.makefile_cb.setObjectName("makefile_cb")
        self.gridLayout_4.addWidget(self.makefile_cb, 5, 0, 1, 2)
        self.scripts_cb = QtWidgets.QCheckBox(parent=self.page2)
        self.scripts_cb.setChecked(True)
        self.scripts_cb.setObjectName("scripts_cb")
        self.gridLayout_4.addWidget(self.scripts_cb, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.optional_items_label = QtWidgets.QLabel(parent=self.page3)
        font = QtGui.QFont()
        font.setBold(True)
        self.optional_items_label.setFont(font)
        self.optional_items_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.optional_items_label.setObjectName("optional_items_label")
        self.gridLayout_2.addWidget(self.optional_items_label, 0, 0, 1, 2)
        self.tracker_label = QtWidgets.QLabel(parent=self.page3)
        self.tracker_label.setMinimumSize(QtCore.QSize(0, 0))
        self.tracker_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tracker_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.tracker_label.setObjectName("tracker_label")
        self.gridLayout_2.addWidget(self.tracker_label, 1, 0, 1, 1)
        self.tracker = QtWidgets.QLineEdit(parent=self.page3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tracker.sizePolicy().hasHeightForWidth())
        self.tracker.setSizePolicy(sizePolicy)
        self.tracker.setMinimumSize(QtCore.QSize(0, 0))
        self.tracker.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tracker.setObjectName("tracker")
        self.gridLayout_2.addWidget(self.tracker, 1, 1, 1, 1)
        self.repository_label = QtWidgets.QLabel(parent=self.page3)
        self.repository_label.setMinimumSize(QtCore.QSize(0, 0))
        self.repository_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.repository_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.repository_label.setObjectName("repository_label")
        self.gridLayout_2.addWidget(self.repository_label, 2, 0, 1, 1)
        self.repository = QtWidgets.QLineEdit(parent=self.page3)
        self.repository.setMinimumSize(QtCore.QSize(0, 0))
        self.repository.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.repository.setObjectName("repository")
        self.gridLayout_2.addWidget(self.repository, 2, 1, 1, 1)
        self.optional_items_label_2 = QtWidgets.QLabel(parent=self.page3)
        font = QtGui.QFont()
        font.setBold(True)
        self.optional_items_label_2.setFont(font)
        self.optional_items_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.optional_items_label_2.setObjectName("optional_items_label_2")
        self.gridLayout_2.addWidget(self.optional_items_label_2, 3, 0, 1, 2)
        self.homepage_label = QtWidgets.QLabel(parent=self.page3)
        self.homepage_label.setMinimumSize(QtCore.QSize(0, 0))
        self.homepage_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.homepage_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.homepage_label.setObjectName("homepage_label")
        self.gridLayout_2.addWidget(self.homepage_label, 4, 0, 1, 1)
        self.homepage = QtWidgets.QLineEdit(parent=self.page3)
        self.homepage.setMinimumSize(QtCore.QSize(80, 0))
        self.homepage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.homepage.setObjectName("homepage")
        self.gridLayout_2.addWidget(self.homepage, 4, 1, 1, 1)
        self.tags_label = QtWidgets.QLabel(parent=self.page3)
        self.tags_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tags_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.tags_label.setObjectName("tags_label")
        self.gridLayout_2.addWidget(self.tags_label, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tags = QtWidgets.QLineEdit(parent=self.page3)
        self.tags.setMinimumSize(QtCore.QSize(0, 0))
        self.tags.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tags.setObjectName("tags")
        self.horizontalLayout_2.addWidget(self.tags)
        self.select_tags = QtWidgets.QToolButton(parent=self.page3)
        self.select_tags.setObjectName("select_tags")
        self.horizontalLayout_2.addWidget(self.select_tags)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 1, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.page3)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.experimental = QtWidgets.QCheckBox(parent=self.frame)
        self.experimental.setObjectName("experimental")
        self.gridLayout_8.addWidget(self.experimental, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 6, 0, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_2.addItem(spacerItem6, 7, 2, 1, 1)
        self.optional_items_label.raise_()
        self.tracker_label.raise_()
        self.tracker.raise_()
        self.homepage_label.raise_()
        self.homepage.raise_()
        self.repository_label.raise_()
        self.repository.raise_()
        self.tags_label.raise_()
        self.optional_items_label_2.raise_()
        self.frame.raise_()
        self.stackedWidget.addWidget(self.page3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.output_directory_label = QtWidgets.QLabel(parent=self.page_4)
        font = QtGui.QFont()
        font.setBold(True)
        self.output_directory_label.setFont(font)
        self.output_directory_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.output_directory_label.setObjectName("output_directory_label")
        self.verticalLayout.addWidget(self.output_directory_label)
        self.label = QtWidgets.QLabel(parent=self.page_4)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.output_directory = QtWidgets.QLineEdit(parent=self.page_4)
        self.output_directory.setObjectName("output_directory")
        self.horizontalLayout.addWidget(self.output_directory)
        self.btn_select_output = QtWidgets.QToolButton(parent=self.page_4)
        self.btn_select_output.setObjectName("btn_select_output")
        self.horizontalLayout.addWidget(self.btn_select_output)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(parent=self.page_4)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lbl_full_output_path = QtWidgets.QLabel(parent=self.page_4)
        self.lbl_full_output_path.setText("")
        self.lbl_full_output_path.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_full_output_path.setWordWrap(True)
        self.lbl_full_output_path.setObjectName("lbl_full_output_path")
        self.verticalLayout.addWidget(self.lbl_full_output_path)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 4)
        self.plugin_name_label.setBuddy(self.title)
        self.class_name_label.setBuddy(self.class_name)
        self.plugin_version_label.setBuddy(self.plugin_version)
        self.author_label.setBuddy(self.author)
        self.module_name_label.setBuddy(self.module_name)
        self.email_address_label.setBuddy(self.email_address)
        self.qgis_minimum_version_label.setBuddy(self.qgis_minimum_version)
        self.description_label.setBuddy(self.description)
        self.template_label.setBuddy(self.template_cbox)

        self.retranslateUi(PluginBuilderDialogBase)
        self.stackedWidget.setCurrentIndex(0)
        self.button_box2.rejected.connect(PluginBuilderDialogBase.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PluginBuilderDialogBase)
        PluginBuilderDialogBase.setTabOrder(self.class_name, self.title)
        PluginBuilderDialogBase.setTabOrder(self.title, self.description)
        PluginBuilderDialogBase.setTabOrder(self.description, self.module_name)
        PluginBuilderDialogBase.setTabOrder(self.module_name, self.plugin_version)
        PluginBuilderDialogBase.setTabOrder(
            self.plugin_version, self.qgis_minimum_version
        )
        PluginBuilderDialogBase.setTabOrder(self.qgis_minimum_version, self.author)
        PluginBuilderDialogBase.setTabOrder(self.author, self.email_address)
        PluginBuilderDialogBase.setTabOrder(self.email_address, self.about)
        PluginBuilderDialogBase.setTabOrder(self.about, self.tracker)
        PluginBuilderDialogBase.setTabOrder(self.tracker, self.repository)
        PluginBuilderDialogBase.setTabOrder(self.repository, self.homepage)
        PluginBuilderDialogBase.setTabOrder(self.homepage, self.tags)
        PluginBuilderDialogBase.setTabOrder(self.tags, self.experimental)
        PluginBuilderDialogBase.setTabOrder(self.experimental, self.scripts_cb)
        PluginBuilderDialogBase.setTabOrder(self.scripts_cb, self.tests_cb)
        PluginBuilderDialogBase.setTabOrder(self.tests_cb, self.next_button)
        PluginBuilderDialogBase.setTabOrder(self.next_button, self.prev_button)
        PluginBuilderDialogBase.setTabOrder(self.prev_button, self.button_box)
        PluginBuilderDialogBase.setTabOrder(self.button_box, self.button_box2)
        PluginBuilderDialogBase.setTabOrder(self.button_box2, self.i18n_cb)
        PluginBuilderDialogBase.setTabOrder(self.i18n_cb, self.template_cbox)
        PluginBuilderDialogBase.setTabOrder(self.template_cbox, self.makefile_cb)
        PluginBuilderDialogBase.setTabOrder(self.makefile_cb, self.select_tags)
        PluginBuilderDialogBase.setTabOrder(self.select_tags, self.pb_tool_cb)
        PluginBuilderDialogBase.setTabOrder(self.pb_tool_cb, self.help_cb)

    def retranslateUi(self, PluginBuilderDialogBase):
        _translate = QtCore.QCoreApplication.translate
        PluginBuilderDialogBase.setWindowTitle(
            _translate("PluginBuilderDialogBase", "QGIS Plugin Builder")
        )
        self.next_button.setText(_translate("PluginBuilderDialogBase", "Next >"))
        self.prev_button.setText(_translate("PluginBuilderDialogBase", "<Previous"))
        self.title_label.setText(
            _translate(
                "PluginBuilderDialogBase",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Sans Serif'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:16pt; font-weight:600;">QGIS Plugin Builder</span></p></body></html>',
            )
        )
        self.module_name.setToolTip(
            _translate(
                "PluginBuilderDialogBase",
                "This is the python module name for your plugin. It should be lower case\n"
                "underscore separated e.g. photo_linker.",
            )
        )
        self.module_name.setPlaceholderText(
            _translate("PluginBuilderDialogBase", "e.g. photo_linker")
        )
        self.description.setToolTip(
            _translate(
                "PluginBuilderDialogBase",
                "A one-liner description of the plugin that appears in the Plugin\n"
                'Manager e.g. "The photo linker plugin lets you link photos to\n'
                'points."',
            )
        )
        self.description.setPlaceholderText(
            _translate(
                "PluginBuilderDialogBase", "e.g. This plugin links points to photos"
            )
        )
        self.author.setToolTip(
            _translate(
                "PluginBuilderDialogBase",
                "Your name or company name (used in the copyright header) e.g.\n"
                "Acme Corp.",
            )
        )
        self.author.setPlaceholderText(
            _translate("PluginBuilderDialogBase", "e.g. Acme widgets Inc.")
        )
        self.plugin_name_label.setText(
            _translate("PluginBuilderDialogBase", "Plugin name")
        )
        self.class_name_label.setText(
            _translate("PluginBuilderDialogBase", "Class name")
        )
        self.email_address.setToolTip(
            _translate(
                "PluginBuilderDialogBase",
                "<html><head/><body><p>Your email address (used in the copyright header) e.g. jack@qgis</p><p>.org</p></body></html>",
            )
        )
        self.email_address.setPlaceholderText(
            _translate("PluginBuilderDialogBase", "e.g. jack@qgis.org")
        )
        self.plugin_version_label.setText(
            _translate("PluginBuilderDialogBase", "Version number")
        )
        self.qgis_minimum_version.setToolTip(
            _translate(
                "PluginBuilderDialogBase",
                "Minimum QGIS minor version required for this plugin to work e.g. 4.0",
            )
        )
        self.qgis_minimum_version.setText(_translate("PluginBuilderDialogBase", "4.0"))
        self.qgis_minimum_version.setPlaceholderText(
            _translate("PluginBuilderDialogBase", "e.g. 4.0")
        )
        self.author_label.setText(
            _translate("PluginBuilderDialogBase", "Author/Company")
        )
        self.module_name_label.setText(
            _translate("PluginBuilderDialogBase", "Module name")
        )
        self.title.setToolTip(
            _translate(
                "PluginBuilderDialogBase",
                "This is the name for your plugin that will be displayed in the QGIS\n"
                "Plugin Manager and the Plugins menu e.g. Photo Linker",
            )
        )
        self.title.setPlaceholderText(
            _translate("PluginBuilderDialogBase", "e.g. Photo Linker")
        )
        self.email_address_label.setText(
            _translate("PluginBuilderDialogBase", "Email address")
        )
        self.plugin_version.setToolTip(
            _translate(
                "PluginBuilderDialogBase",
                "The version of this plugin using semantic versioning (see\n"
                "http://semver.org) e.g. 0.1.1",
            )
        )
        self.plugin_version.setText(_translate("PluginBuilderDialogBase", "0.1"))
        self.plugin_version.setPlaceholderText(
            _translate("PluginBuilderDialogBase", "e.g. 0.1.0")
        )
        self.class_name.setToolTip(
            _translate(
                "PluginBuilderDialogBase",
                "This is the Python class name for your plugin.\n"
                "It should be in CamelCase e.g. PhotoLinker.",
            )
        )
        self.class_name.setPlaceholderText(
            _translate("PluginBuilderDialogBase", "e.g. PhotoLinker")
        )
        self.qgis_minimum_version_label.setText(
            _translate("PluginBuilderDialogBase", "Minimum QGIS version")
        )
        self.description_label.setText(
            _translate("PluginBuilderDialogBase", "Description")
        )
        self.qgis_maximum_version_label.setText(
            _translate("PluginBuilderDialogBase", "Maximum QGIS version")
        )
        self.qgis_maximum_version.setText(_translate("PluginBuilderDialogBase", "4.99"))
        self.groupBox.setTitle(_translate("PluginBuilderDialogBase", "About"))
        self.about.setToolTip(
            _translate(
                "PluginBuilderDialogBase",
                "<html><head/><body><p>Enter a long description for your plugin to provide details about its purpose.</p></body></html>",
            )
        )
        self.about.setPlainText(
            _translate(
                "PluginBuilderDialogBase",
                "Provide a brief description of the plugin and its purpose.",
            )
        )
        self.template_label.setText(_translate("PluginBuilderDialogBase", "Template"))
        self.help_cb.setText(_translate("PluginBuilderDialogBase", "Help"))
        self.tests_cb.setText(_translate("PluginBuilderDialogBase", "Unit tests"))
        self.i18n_cb.setText(
            _translate("PluginBuilderDialogBase", "Internationalization")
        )
        self.pb_tool_cb.setText(_translate("PluginBuilderDialogBase", "pb_tool"))
        self.makefile_cb.setText(_translate("PluginBuilderDialogBase", "Makefile"))
        self.scripts_cb.setText(_translate("PluginBuilderDialogBase", "Helper scripts"))
        self.optional_items_label.setText(
            _translate("PluginBuilderDialogBase", "Publication (mandatory Items)")
        )
        self.tracker_label.setText(_translate("PluginBuilderDialogBase", "Bug tracker"))
        self.tracker.setToolTip(
            _translate("PluginBuilderDialogBase", "Url of your plugin's bug tracker")
        )
        self.tracker.setPlaceholderText(
            _translate(
                "PluginBuilderDialogBase", "Consider using github.com for tracking"
            )
        )
        self.repository_label.setText(
            _translate("PluginBuilderDialogBase", "Repository")
        )
        self.repository.setToolTip(
            _translate(
                "PluginBuilderDialogBase",
                "Url of your plugin repository (if you have one)",
            )
        )
        self.repository.setPlaceholderText(
            _translate(
                "PluginBuilderDialogBase",
                "Consider using github.com to store your code",
            )
        )
        self.optional_items_label_2.setText(
            _translate("PluginBuilderDialogBase", "Publication (recommended Items)")
        )
        self.homepage_label.setText(_translate("PluginBuilderDialogBase", "Home page"))
        self.homepage.setToolTip(
            _translate("PluginBuilderDialogBase", "Url of your plugin's home page")
        )
        self.homepage.setPlaceholderText(
            _translate(
                "PluginBuilderDialogBase", "Your GitHub repository can be the home page"
            )
        )
        self.tags_label.setText(_translate("PluginBuilderDialogBase", "Tags"))
        self.tags.setToolTip(
            _translate(
                "PluginBuilderDialogBase",
                "A comma separated list of tags that describe the plugin features or function",
            )
        )
        self.tags.setText(_translate("PluginBuilderDialogBase", "python"))
        self.tags.setPlaceholderText(
            _translate(
                "PluginBuilderDialogBase", "Select tags from a list or enter your own"
            )
        )
        self.select_tags.setToolTip(
            _translate("PluginBuilderDialogBase", "Select tags")
        )
        self.select_tags.setText(_translate("PluginBuilderDialogBase", "..."))
        self.experimental.setText(
            _translate("PluginBuilderDialogBase", "Flag the plugin as experimental")
        )
        self.output_directory_label.setText(
            _translate("PluginBuilderDialogBase", "Select Output Directory")
        )
        self.label.setText(
            _translate(
                "PluginBuilderDialogBase",
                "Your plugin is ready to be generated. Select the output directory.",
            )
        )
        self.btn_select_output.setText(_translate("PluginBuilderDialogBase", "..."))
        self.label_2.setText(
            _translate(
                "PluginBuilderDialogBase",
                "Your plugin will be created in the selected location, using the module name for the name of the subdirectory.",
            )
        )
