# Form implementation generated from reading ui file 'select_tags_dialog_base.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtWidgets


class Ui_dlgSelectTags(object):
    def setupUi(self, dlgSelectTags):
        dlgSelectTags.setObjectName("dlgSelectTags")
        dlgSelectTags.resize(320, 384)
        self.gridLayout = QtWidgets.QGridLayout(dlgSelectTags)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=dlgSelectTags)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.listView = QtWidgets.QListView(parent=dlgSelectTags)
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.listView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dlgSelectTags)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        buttons = (
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.buttonBox.setStandardButtons(buttons)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(dlgSelectTags)
        self.buttonBox.accepted.connect(dlgSelectTags.accept)  # type: ignore
        self.buttonBox.rejected.connect(dlgSelectTags.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgSelectTags)

    def retranslateUi(self, dlgSelectTags):
        _translate = QtCore.QCoreApplication.translate
        dlgSelectTags.setWindowTitle(_translate("dlgSelectTags", "Select Tags"))
        self.label.setText(_translate("dlgSelectTags", "Select one or more tags"))
